// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOLklyKNitspiqiWHNwJ6OQOiy964Vcpg',
    appId: '1:896261439291:web:23c4d2950fa1109065811e',
    messagingSenderId: '896261439291',
    projectId: 'learn-n-database',
    authDomain: 'learn-n-database.firebaseapp.com',
    storageBucket: 'learn-n-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHNMG2JipW2waU25edeEpT3chCloe3qdY',
    appId: '1:896261439291:android:012379d62b69521f65811e',
    messagingSenderId: '896261439291',
    projectId: 'learn-n-database',
    storageBucket: 'learn-n-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvnnCL9whCTsgqUQQIOdOGMNFWU34-_jg',
    appId: '1:896261439291:ios:405647bf4574925d65811e',
    messagingSenderId: '896261439291',
    projectId: 'learn-n-database',
    storageBucket: 'learn-n-database.firebasestorage.app',
    iosBundleId: 'com.example.learnNApp',
  );
}
